version: "3.9"

services:
  backend:
    build:
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  db_data:
  redis_data:













# version: "3.9"

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - SECRET=your-secret-key-change-in-production
#       - DEBUG=on
#       - REDIS_URL=redis://redis:6379/9
#     depends_on:
#       - redis

#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379"



# version: "3.9"
 
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - redis
 
#   celery:
#     build: .
#     command: celery -A config worker --loglevel=info
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     depends_on:
#       - redis
 
#   celery-beat:
#     build: .
#     command: celery -A config beat --loglevel=info
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     depends_on:
#       - redis
 
#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379"